---

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      exposure:
        include: "*"
